### ISSUE TITLE
FLower_1 inspect method failed 

### ISSUE THREAD

**Issue by Testing2DataScience** [UltimateSoftware/AGENT#4]
After getting connected to rabbitmq ,stats,active_queues,registered ,schedules inspect method failed 
while running --- docker-compose -f docker-compose-dev.yml up --force-recreate --build
Script not moving further . 

CPU's used 4 Memory -8192MB

![image](https://user-images.githubusercontent.com/42400801/53487848-aea2b800-3ab2-11e9-8e64-2d941f09fc53.png)

**Comment by Castyr** [comment]
How much RAM do you have on your system, this might be due to a low amount of RAM being available for Docker even though you have set it to 8GB. The messages you are seeing happen a lot and need to be resolved, but they are not the problem.

**Comment by Testing2DataScience** [comment]
I am having 16 gb ram on my machine.

**Comment by Chraneco** [comment]
Did you do step 5 of the README? Your log outputs indicates that the system is currently waiting for being given a URL.

**Comment by Testing2DataScience** [comment]
yes  i did that . Now i tried again starting from step1 and getting below error on flower_1
![image](https://user-images.githubusercontent.com/42400801/53855642-822bf600-3ff4-11e9-8994-7635cec482af.png)

**Comment by Testing2DataScience** [comment]
Hi team - is there any update on this ? can u plz help in building the project.

**Comment by dsant005** [comment]
We are currently looking into this. It appears a new release of the Tornado dependency is causing problems.

**Comment by Testing2DataScience** [comment]
any updates please.

**Comment by Testing2DataScience** [comment]
Hi dsant005 - were you able to fix the tornado dependency issue.

**Comment by Testing2DataScience** [comment]
Hello guys - do you think this issue will be fixed some time soon .

**Comment by Testing2DataScience** [comment]
Hi -  Is there any update on this .Can we expect a resolution for this issue.

**Comment by dsant005** [comment]
Should be resolved by commit c8a78cc3ccbb4043e986fcfde7ee01766c273621.
Please pull and follow the developer install instructions once again.

**Comment by Testing2DataScience** [comment]
Hi 
Tried building the project with newer flower dependency (flower==0.9.3
redis==3.0.1)  but still getting similar type of error .

Ram allocated to docker 12 GB ( of 16GB) and cpu assigned 4 .Kindly have a look.

![image](https://user-images.githubusercontent.com/42400801/57073219-0bfaf580-6cfe-11e9-93b5-42e3f043ed64.png)
